import React, {useEffect, useState} from 'react';
import { useNavigate } from 'react-router-dom';
import { ethers } from 'ethers';
import './styles/main.css'


export const Main = () => {

    const [ loading, setLoading ] = useState(true)
    const [ walletAddress, setWalletAddress ] = useState('Connect Wallet')
    const [ errMessage, setErrMessage ] = useState('')
    const [ isHasAddress, setisHasAddress ] = useState(false)

    let nav = useNavigate()

    async function connectWallet() {
        if (window.ethereum) {
          try {
            // Request account access
            const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
            
            // Wallet connected successfully
            console.log('Wallet connected!');
            setWalletAddress(shortedAddress(accounts[0]))
            // Create an ethers.js provider
            const provider = new ethers.BrowserProvider(window.ethereum);
            
            // You can now use the provider to interact with the Ethereum network
            // For example, you can get the signer's address:
            const signerAddress = await provider.getSigner().getAddress();
            console.log('Signer address:', signerAddress);
            
          } catch (error) {
            console.error('Error connecting wallet:', error);
          }
        } else {
          console.error('MetaMask not detected. Please install MetaMask extension.');
          setErrMessage('MetaMask not detected. Please install MetaMask extension')
        }
      }

      const shortedAddress = (address) => {
        if (address.substring(0,2) === '0x' && address.length === 42){
            setErrMessage('')
            setisHasAddress(true)
            return address.substring(0,4) + '....' + address.substring(38)
        }else{
            setisHasAddress(false)
            return 'Connect Wallet'
        }
      }


    return (
    
        <div className='main-cnt'>
            <div className='h-line'>
                <div className='header'>
                    <h3>LIMITLESS<br/>SUSTAINABLITY<br/>FOR ALL</h3>
                </div>
                <div className='img-cnt'>
                    <img className="logo" src="/logobrain.png" alt="Logo" />
                </div>
            </div>
            
            <div className='secondary-cnt'>
                <div className='s-cnt-1'>
                    <div className='title'>
                        <h1>MINT YOURS</h1>
                    </div>
                    <div>
                        <p>
                        FOUNDERS NFTs are a new class of NFTs that aim to provide a long-term income stream for their holders by sharing a portion of the revenue generated by the underlying asset. The income generated by these NFTs can help to create a stable financial foundation for the holder and their future generations.
                        </p>
                    </div>
                    <div className='btn-cnt'>
                        <span className='err'>{ errMessage }</span>
                        <button className='btn' onClick={() => {
                            isHasAddress? nav('/mint') : connectWallet()
                        } }>{ walletAddress }</button>
                    </div>
                </div>
                <div className='card'>
                    <img className='nft' src='/foundersNFT.png' alt="NFT"/>
                    <div className='c-title'>
                        <span className='card-span'>FOUNDERS NFT</span>
                    </div>
                </div>
            </div>

        </div>


    )
}